name: Gather-Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      shell: bash
          
    - name: Checkout
      uses: actions/checkout@v4

    # Alternative approach to install github-linguist as a gem (with no caching)
    # - name: Install Linguist
    #   run: |
    #     sudo gem install github-linguist
    #     sudo gem env
    #     # which github-linguist
    #     # du -sh /usr/local/bin/
    #   shell: bash

    # Install github-linguist (with caching)
    - name: Setup Ruby and install github-linguist
      uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 3.2
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true

      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        # Install ghlinguist from personal repo
        git clone https://github.com/DecimalTurn/linguist-python.git --depth 1
        cd linguist-python
        # Make your code changes here
        pip install .
        cd ..
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Python script
      run: |
        python run.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
    - name: Push content
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
        # Run git add data/data.csv but don't fail if there are no changes
        git add data/ || echo "---"
        git add date.txt || echo "---"
        git add disable.txt || echo "---"
        git add retries.txt || echo "---"
        git add charts/ || echo "---"

        # Get the list of staged files
        staged_files=$(git diff --cached --name-only)

        if [ -n "$staged_files" ]; then
          echo "Changes detected"

          # Check if the only staged file is retries.txt
          if [ "$staged_files" = "retries.txt" ]; then
            commit_message="Update retry counter"
          else
            commit_message="Update data"
          fi

          git commit -m "$commit_message"
          git push --set-upstream origin main
        else
          echo "No changes to commit"
        fi
      shell: bash
