name: Gather-Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      shell: bash
          
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 3.3
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true

    - name: Update PATH for bundled gems
      run: |
        export PATH="$PWD/vendor/bundle/ruby/3.3.0/bin:$PATH"
        echo $PATH
        # echo 'export PATH=$PWD/vendor/bundle/ruby/3.3.0/bin:$PATH' >> $GITHUB_ENV
        github-linguist --version
      shell: bash
      
#    - name: Install Linguist
#      run: |
#        sudo gem install github-linguist
#        sudo gem env
#      shell: bash

      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Run script
      run: |
        pip install requests
        git clone https://github.com/DecimalTurn/linguist-python.git --depth 1
        cd linguist-python
        # Make your code changes here
        pip install .
        cd ..
        python run.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push content
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
        # Run git add data/2019.csv but don't fail if there are no changes
        git add data/ || echo "---"
        git add date.txt || echo "---"
        git add disable.txt || echo "---"

        git status
        if [ -n "$(git diff --cached --exit-code)" ]; then
          echo "Changes detected"
          git add data/2019.csv
          commit_message=$(printf "Update data")
          git commit -m "$commit_message" 
          git push --set-upstream origin main
        else
          echo "No changes to commit"
        fi
      shell: bash
