name: Gather-Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
    
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      shell: bash
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4' # Specify the Ruby version you need

    - name: Cache Ruby gems
      id: cache-gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    - name: Install linguist
      run: gem install linguist
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Run script
      run: |
        pip install requests
        git clone https://github.com/DecimalTurn/linguist-python.git --depth 1
        cd linguist-python
        # Make your code changes here
        pip install .
        cd ..
        python run.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push content
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
        # Run git add data/2019.csv but don't fail if there are no changes
        git add data/ || echo "---"
        git add date.txt || echo "---"
        git add disable.txt || echo "---"

        git status
        if [ -n "$(git diff --cached --exit-code)" ]; then
          echo "Changes detected"
          git add data/2019.csv
          commit_message=$(printf "Update data")
          git commit -m "$commit_message" 
          git push --set-upstream origin main
        else
          echo "No changes to commit"
        fi
      shell: bash
