name: Gather-Data

on:
  workflow_dispatch:

jobs:
  gather-data:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      shell: bash
    - name: Install Linguist
      run: |
        sudo gem install github-linguist
        sudo gem env
      shell: bash    
    - name: Checkout
      if: ${{ inputs.do-checkout }}
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Run script
      run: |
        python '${{ github.action_path }}/run.py'
      shell: bash
    - name: Push content
      run: |
        git config user.name "${{ inputs.bot-name }}"
        git config user.email "${{ inputs.bot-email }}"
      
        git status
        if [ -n "$(git diff --cached --exit-code)" ]; then
          echo "Changes detected"
          git add results.txt
          commit_message=$(printf "Update data")
          git commit -m "$commit_message" 
          git push --set-upstream origin main
        else
          echo "No changes to commit"
        fi
      shell: bash